class Strings {
  static const String fonte_cprm = "Fonte das informações: CPRM - Companhia de Pesquisa de Recursos Minerais";
  static const String url_imagem = "http://sgm.ouropreto.mg.gov.br/arquivos/defesa_civil/imagens/";
  //<string name="fonte_cprm">Fonte das informações: CPRM - Companhia de Pesquisa de Recursos Minerais</string>
  static const String importante = "IMPORTANTE: A abertura ou fechamento de um dos níveis do Alerta Meteorológico não está vinculado exclusivamente ao volume de chuva acumulado no dia anterior. Para as alterações dos níveis do Alerta Meteorológico também são levados em consideração os monitoramentos em campo a fim de verificar visualmente o afloramento do nível freático nos taludes da cidade. Essa conduta é de grande importância, visto que assim pode-se verificar como está a elevação do nível freático durante o período chuvoso, processo importante na deflagração dos movimentos de massa. Quando o Alerta Meteorológico entra em seus níveis extremos, por exemplo, no de alerta máximo com cor vermelha, significa que naquelas condições de chuvas acidentes significativos com deslizamentos de encostas já ocorreram em Ouro Preto em algum momento do passado. Desta forma, podem ou não ocorrer deslizamentos de encostas durante um nível extremo do Alerta Meteorológico, sendo que as probabilidades de ocorrências destes movimentos de massa são maiores nestas condições de chuvas. A intenção principal é alertar a população quanto aos riscos a que ela está exposta naquelas condições críticas de chuva, sendo que sempre almejamos que nenhuma fatalidade ocorra até o cessar do alerta máximo. Outra informação relevante é que nos primeiros níveis do alerta, por exemplo, no de atenção com cor amarela, podem ocorrer deslizamentos de encostas mesmo com as baixas probabilidades destas ocorrências neste nível do alerta meteorológico. Isso se deve ao fato de que mesmo não havendo frentes frias associadas às Zonas de Convergências do Atlântico Sul (Zcas) atuando sobre nossa região, fenômenos indicadores de chuvas intensas e duradouras, as pancadas de chuvas no final das tardes do verão, conhecidas como chuvas convectivas, podem apresentar acumulados expressivos que caem em um curto intervalo de tempo e geralmente vêm acompanhadas de fortes rajadas de ventos e até mesmo de granizo. Esse tipo de chuva pode ter grande potencial destrutivo, principalmente se o terreno já estiver encharcado devido às chuvas dos dias anteriores, com potencial para causar deslizamentos, enchentes e enxurradas. Fique Atento!O nosso maior objetivo é analisar, todos os dias, o volume de chuva que caiu em Ouro Preto no dia anterior. Com isso, podemos verificar se essa chuva que caiu poderá ou não causar deslizamentos de encostas em nossa cidade. Se a chuva foi perigosa, emitiremos imediatamente alertas pelo melhor meio de comunicação local que estiver disponível no momento. Para quem quiser saber maiores detalhes sobre a previsão do tempo específica para Ouro Preto, deixamos disponível um link do CPTEC/INPE na página principal da Prefeitura Municipal de Ouro Preto. Não se deve confundir o Alerta Meteorológico com previsão do tempo. A previsão do tempo é apenas uma das ferramentas utilizadas na atualização do Alerta Meteorológico.";
  static const String verde = "VERDE (Observação) - Neste nível é feito o monitoramento meteorológico constante, a fim de verificar e antecipar a formação de sistemas atmosféricos frontais (frentes frias) que avançam sentido a Região Sudeste e que podem gerar acumulados significativos de chuvas. Os sistemas que mais preocupam são aqueles associados aos corredores de umidade provenientes da Região Amazônica que formam as Zonas de Convergência do Atlântico Sul (Zcas). Os acumulados de chuva nestes períodos geralmente são significativos e provocam o encharcamento excessivo do solo. Isso favorece os deslizamentos de terra, bem como o rolamento de blocos rochosos";
  static const String amarelo = "AMARELO (Atenção) – Entra-se neste nível quando o índice pluviométrico monitorado varia de 0 a 22 mmacumulados de chuvas em um período de cinco dias consecutivos. Neste estágio é iniciado o Plano de Contingência Municipal com acompanhamento dos índices pluviométricos e dos boletins meteorológicos que são emitidos pelos órgãos estaduais e federais";
  static const String laranja = "LARANJA (Alerta) – Entra-se neste nível quando o índice pluviométrico monitorado varia de 22 a 128 mmacumulados de chuvas em um período de cinco dias consecutivos. Neste nível de alerta, deslizamentos de terra e rolamento de blocos rochosos podem ocorrer isoladamente. Este nível é caracterizado por chuvas prolongadas e requer um maior acompanhamento dos índices pluviométricos e dos boletins meteorológicos que são emitidos pelos órgãos estaduais e federais. Neste estágio existe a probabilidade isolada de remoções preventivas de alguns moradores das áreas de risco mapeadas, a fim de resguardar a integridade física dos mesmos";
  static const String vermelho = "VERMELHO (Alerta Máximo) - Entra-se neste nível quando o índice pluviométrico ultrapassar a marca monitorada de128 mmacumulados de chuvas em um período de cinco dias consecutivos. Neste nível de alerta, deslizamentos de terra e rolamento de blocos rochosos com maior expressão podem ocorrer de modo generalizado em toda a cidade nas áreas de risco mapeadas. Este nível é caracterizado por chuvas prolongadas e com previsão de continuidade para os próximos dias. Essa situação exige um criterioso acompanhamento dos índices pluviométricos e dos boletins meteorológicos que são emitidos pelos órgãos estaduais e federais. Neste estágio existe a probabilidade de remoções generalizadas preventivas e definitivas dos moradores das áreas de risco já mapeadas, a fim de resguardar a integridade física da população;OBS.:É importante salientar que podem ocorrer casos isolados fora do padrão exposto em cada nível citado acima, uma vez que os valores de referência foram estabelecidos a partir de análise estatística e probabilística por meio do estudo de dados coletados durante 17 anos de observações. As margens de erro verificadas durante os estudos que foram desenvolvidos são da ordem de10%aproximadamente.";
  static const String observacaoPluv = "IMPORTANTE: Para os pluviômetros individuais, o nível de Alerta Metereológico é automático e não são levados em consideração outros monitoramentos ou análises";


}